# Generated by Django 4.1.3 on 2022-11-08 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_restaurant_category_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='restaurant',
            field=models.ManyToManyField(related_name='restaurant', to='customer.restaurant'),
        ),
    ]
