# Generated by Django 4.1.3 on 2022-11-15 22:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_remove_restaurant_restaurant_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
