# Generated by Django 4.1.3 on 2022-11-15 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_ordermodel_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='description',
        ),
    ]
